require:
  - rubocop-powerhome

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - "vendor/**/*"
    - "spec/dummy/node_modules/**/*"
    - "spec/dummy/db/schema.rb"

Style/FrozenStringLiteralComment:
  Exclude:
    - "gemfiles/*"

Lint/ToEnumArguments:
  Exclude:
    - "lib/audiences/scim/resources_query.rb"

Bundler/OrderedGems:
  Exclude:
    - "gemfiles/*"

Rails/I18nLocaleTexts:
  Exclude:
    - "spec/dummy/**/*"
