# frozen_string_literal: true

appraise "rails-7-2" do
  gem "rails", "~> 7.2", "< 8.0"
end

appraise "rails-8-0" do
  gem "rails", "~> 8.0", "< 8.1"
end

appraise "rails-8-1" do
  gem "rails", "~> 8.1", "< 8.2"
end
