# frozen_string_literal: true

appraise "rails-6-0" do
  gem "rails", "~> 6.0", "< 6.1"
  gem "rspec-rails", "~> 5.1.2"
end

appraise "rails-6-1" do
  gem "rails", "~> 6.1"
end

appraise "rails-7-0" do
  gem "rails", "~> 7.0", "< 7.1"
end
