# frozen_string_literal: true

appraise "rails-6-1" do
  gem "rails", "~> 6.1"
end

appraise "rails-7-0" do
  gem "rails", "~> 7.0", "< 7.1"
  gem "rspec-rails", "~> 7.0.0"
end

appraise "rails-7-1" do
  gem "rails", "~> 7.1", "< 7.2"
  gem "rspec-rails", "~> 7.0.0"
end
