# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gemspec

# Development tools
gem "appraisal", "~> 2.5.0"
gem "debug", ">= 1.0.0"
gem "foreman", "~> 0.87.2"
gem "license_finder", ">= 7.0"
gem "rails", "~> 6.0.6.1"
gem "rake", ">= 13.0"
gem "rspec", ">= 3.0"
gem "rspec-rails", "~> 5.1.2"
gem "rubocop", ">= 1.32"
gem "rubocop-powerhome"
gem "shoulda-matchers", "~> 5.0"
gem "vite_rails", "~> 3.0"
gem "webmock", "~> 3.18"

# Development environment dependencies
gem "puma", "~> 6.3"
gem "sqlite3"
