# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gemspec

# Development workflow
gem "appraisal", "~> 2.4.1"
gem "foreman", "~> 0.87.2"
gem "license_finder", ">= 7.0"
gem "vite_rails", "~> 3.0"

# Development tools
# gem "debug", ">= 1.0.0"
gem "rake", ">= 13.0"
gem "rspec", ">= 3.0"
gem "rspec-rails", ">= 6.0.3"
gem "rubocop", ">= 1.32"
gem "rubocop-powerhome"
gem "shoulda-matchers", "~> 5.0"

# Development dependencies
gem "puma", "~> 6.3"
gem "sqlite3"
gem "webmock", "~> 3.18"
