# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gemspec

# Development tools
gem "appraisal", "2.5.0"
gem "brakeman", "7.1.0"
gem "debug", "1.10.0"
gem "foreman", "0.88.1"
gem "license_finder", "7.2.1"
gem "rails", "~> 6.1.7.0"
gem "rake", "13.2.1"
gem "rspec", "3.13.0"
gem "rspec-rails", "6.1.5"
gem "rubocop", "1.66.1"
gem "rubocop-powerhome"
gem "shoulda-matchers", "5.3.0"
gem "vite_rails", "3.0.19"
gem "webmock", "3.25.0"

# Development environment dependencies
gem "mysql2", "0.5.6"
gem "pg", "1.5.9"
gem "puma", "6.6.0"
gem "two_percent", "0.4.0"
