#!/usr/bin/env rake

# frozen_string_literal: true

require "logger"
require "bundler/setup"
require "bundler/gem_tasks"

require "rspec/core/rake_task"
RSpec::Core::RakeTask.new(spec: %w[app:db:prepare])

require "rubocop/rake_task"
RuboCop::RakeTask.new(:rubocop)

APP_RAKEFILE = File.expand_path("spec/dummy/Rakefile", __dir__)
load "rails/tasks/engine.rake"
load "rails/tasks/statistics.rake"

desc "Build audiences-react and copy JS to Rails assets"
task build_frontend: :environment do
  puts "Building audiences-react..."
  system("cd ../audiences-react && yarn install && yarn build") || raise("Failed to build audiences-react")

  source_path = "../audiences-react/dist/audiences-ujs.js"
  destination_dir = "app/assets/builds"
  destination_path = "#{destination_dir}/audiences-ujs.js"

  FileUtils.mkdir_p(destination_dir)

  raise "Build file not found: #{source_path}" unless File.exist?(source_path)

  puts "Copying #{source_path} to #{destination_path}..."
  FileUtils.cp(source_path, destination_path)
  puts "Successfully copied!"
end

Rake::Task["build"].enhance(["build_frontend"])

task default: %i[rubocop spec build_frontend]
