name: audiences

on:
  push:

jobs:
  ruby:
    uses: powerhome/github-actions-workflows/.github/workflows/ruby-gem.yml@rubygem-action
    with:
      package: ${{ github.workflow }}
      workdir: ${{ github.workflow }}
      before_build: 'sudo /etc/init.d/mysql start && sudo apt-get install libpq-dev'
      gemfiles: "['gemfiles/rails_6_1.gemfile','gemfiles/rails_7_0.gemfile','gemfiles/rails_7_1.gemfile']"
      ruby: '["3.0","3.1","3.2","3.3"]'
      exclude: |-
        [
          { 'ruby': '3.2', 'gemfile': 'gemfiles/rails_6_1.gemfile'},
          { 'ruby': '3.3', 'gemfile': 'gemfiles/rails_6_1.gemfile'},
        ]
    secrets: inherit
