name: audiences-react

on:
  push:

jobs:
  node:
    uses: powerhome/github-actions-workflows/.github/workflows/yarn-package.yml@main
    with:
      workdir: "${{ github.workflow }}"
    secrets: inherit
